[[redirects]]
  from = "/current-map/*"
  to = "https://current-map.netlify.app/current-map/:splat"
  status = 200

[[redirects]]
  from = "/lake-stats/*"
  to = "https://goboard-production.up.railway.app/lake-stats/:splat"
  status = 200
