[[redirects]]
  from = "/current/*"
  to = "https://goboard-production.up.railway.app/current-map/:splat"
  status = 200

[[redirects]]
  from = "/lake-stats/*"
  to = "https://goboard-production.up.railway.app/:splat"
  status = 200
